export { default as gitHubLogo } from './logos/github.svg'
export { default as linkedInLogo } from './logos/linkedin.svg'
export { default as instagramLogo } from './logos/instagram.svg'
export { default as telegramLogo } from './logos/telegram.svg'
export { default as twitchLogo } from './logos/twitch.svg'
export { default as profilePicture } from './profilePicture.jpg'